### ISSUE TITLE
Issue của Sinh từ 11/3 -> 17/3

### ISSUE THREAD

**Issue by sinh2206** [HienNguyenPhan/LearnEase#3]
Học chương 3 và chương 9 môn CNPM
Học về framework và cách training data -> chọn được framework TensorFlow
Phân tích dữ liệu → ra được điều kiện để tạo ra test

**Comment by htm04** [comment]
- hỏi thầy Minh

**Comment by sinh2206** [comment]
Cố gắng demo vào giữa tuần sau

**Comment by htm04** [comment]
đến 24.3

**Comment by sinh2206** [comment]
1/4 - 14/4 : Học chắc kiến thức chương 3 và chương 9 của môn
Tìm kiếm nguồn data

**Comment by sinh2206** [comment]
Hoàn thành
